### ISSUE TITLE
Unable to get the file tangible.Azure.Tracing.TraceConsole.exe and associated config file

### ISSUE THREAD

**Issue by rituja** [Microsoft/microsoft-deployment-accelerator-for-hybris-on-azure#4]
Hello,

I am trying to deploy Hybris on Azure and although Deployment is successful I am getting 404 error while accessing the landing page (hybris console).
In order to debug the error  I need tangible.Azure.Tracing.TraceConsole.exe and associated config files .Please help me in locating these files.

Thanks,
Rituja

**Comment by holgerkenn** [comment]
Please see Hybris On Azure.pdf in the root directory of the project for download instructions. (the download link you will find there is https://tangibletransfer.blob.core.windows.net/public/tangible.Azure.Tracing.TraceConsole.zip )
